name: server
version: '0.1'

dependencies:
  - base
  - bytestring
  - aeson
  - network
  - text
  - interpolatedstring-perl6
  - wai
  - wai-websockets
  - wai-app-static
  - websockets
  - warp

default-extensions:
  - OverloadedStrings
  - ScopedTypeVariables

library:
  source-dirs: src
  exposed-modules:
    - Moba.Server
    - Moba.Server.Internal

executables:
  server:
    main: Main.hs
    ghc-options: -threaded
    dependencies:
      - server
      - fast-logger
      - haskeline
      - optparse-applicative
